{{- if and .Values.persistence.data.enabled (eq .Values.database.backend "sqlite") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shieldoo-gate.fullname" . }}-data
  labels:
    {{- include "shieldoo-gate.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
---
{{- if and .Values.persistence.cache.enabled (eq .Values.cache.backend "local") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shieldoo-gate.fullname" . }}-cache
  labels:
    {{- include "shieldoo-gate.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.cache.accessMode }}
  {{- if .Values.persistence.cache.storageClass }}
  storageClassName: {{ .Values.persistence.cache.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size }}
{{- end }}
