{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shieldoo-gate.fullname" . }}-secrets
  labels:
    {{- include "shieldoo-gate.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.postgresDsn }}
  database-dsn: {{ .Values.secrets.postgresDsn | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.webhookSecret }}
  webhook-secret: {{ .Values.secrets.webhookSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.slackWebhookUrl }}
  slack-webhook-url: {{ .Values.secrets.slackWebhookUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.smtpUsername }}
  smtp-username: {{ .Values.secrets.smtpUsername | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.smtpPassword }}
  smtp-password: {{ .Values.secrets.smtpPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.oidcClientSecret }}
  oidc-client-secret: {{ .Values.secrets.oidcClientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.s3AccessKey }}
  s3-access-key: {{ .Values.secrets.s3AccessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.s3SecretKey }}
  s3-secret-key: {{ .Values.secrets.s3SecretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.azureConnectionString }}
  azure-connection-string: {{ .Values.secrets.azureConnectionString | b64enc | quote }}
  {{- end }}
{{- end }}
