# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import scanner_pb2 as proto_dot_scanner__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/scanner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScannerBridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScanArtifact = channel.unary_unary(
                '/scanner.ScannerBridge/ScanArtifact',
                request_serializer=proto_dot_scanner__pb2.ScanRequest.SerializeToString,
                response_deserializer=proto_dot_scanner__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.ScanArtifactAI = channel.unary_unary(
                '/scanner.ScannerBridge/ScanArtifactAI',
                request_serializer=proto_dot_scanner__pb2.AIScanRequest.SerializeToString,
                response_deserializer=proto_dot_scanner__pb2.AIScanResponse.FromString,
                _registered_method=True)
        self.ScanArtifactDiff = channel.unary_unary(
                '/scanner.ScannerBridge/ScanArtifactDiff',
                request_serializer=proto_dot_scanner__pb2.DiffScanRequest.SerializeToString,
                response_deserializer=proto_dot_scanner__pb2.DiffScanResponse.FromString,
                _registered_method=True)
        self.TriageFindings = channel.unary_unary(
                '/scanner.ScannerBridge/TriageFindings',
                request_serializer=proto_dot_scanner__pb2.TriageRequest.SerializeToString,
                response_deserializer=proto_dot_scanner__pb2.TriageResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/scanner.ScannerBridge/HealthCheck',
                request_serializer=proto_dot_scanner__pb2.HealthRequest.SerializeToString,
                response_deserializer=proto_dot_scanner__pb2.HealthResponse.FromString,
                _registered_method=True)


class ScannerBridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ScanArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanArtifactAI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanArtifactDiff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriageFindings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScannerBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScanArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanArtifact,
                    request_deserializer=proto_dot_scanner__pb2.ScanRequest.FromString,
                    response_serializer=proto_dot_scanner__pb2.ScanResponse.SerializeToString,
            ),
            'ScanArtifactAI': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanArtifactAI,
                    request_deserializer=proto_dot_scanner__pb2.AIScanRequest.FromString,
                    response_serializer=proto_dot_scanner__pb2.AIScanResponse.SerializeToString,
            ),
            'ScanArtifactDiff': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanArtifactDiff,
                    request_deserializer=proto_dot_scanner__pb2.DiffScanRequest.FromString,
                    response_serializer=proto_dot_scanner__pb2.DiffScanResponse.SerializeToString,
            ),
            'TriageFindings': grpc.unary_unary_rpc_method_handler(
                    servicer.TriageFindings,
                    request_deserializer=proto_dot_scanner__pb2.TriageRequest.FromString,
                    response_serializer=proto_dot_scanner__pb2.TriageResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_scanner__pb2.HealthRequest.FromString,
                    response_serializer=proto_dot_scanner__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scanner.ScannerBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scanner.ScannerBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScannerBridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScanArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scanner.ScannerBridge/ScanArtifact',
            proto_dot_scanner__pb2.ScanRequest.SerializeToString,
            proto_dot_scanner__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanArtifactAI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scanner.ScannerBridge/ScanArtifactAI',
            proto_dot_scanner__pb2.AIScanRequest.SerializeToString,
            proto_dot_scanner__pb2.AIScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanArtifactDiff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scanner.ScannerBridge/ScanArtifactDiff',
            proto_dot_scanner__pb2.DiffScanRequest.SerializeToString,
            proto_dot_scanner__pb2.DiffScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriageFindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scanner.ScannerBridge/TriageFindings',
            proto_dot_scanner__pb2.TriageRequest.SerializeToString,
            proto_dot_scanner__pb2.TriageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scanner.ScannerBridge/HealthCheck',
            proto_dot_scanner__pb2.HealthRequest.SerializeToString,
            proto_dot_scanner__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
