// scanner-bridge/proto/scanner.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: scanner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AIScanRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId       string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"` // "ecosystem:name:version"
	Ecosystem        string                 `protobuf:"bytes,2,opt,name=ecosystem,proto3" json:"ecosystem,omitempty"`                     // pypi, npm, nuget, maven, rubygems
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version          string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	LocalPath        string                 `protobuf:"bytes,5,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`                      // path to downloaded artifact on disk
	OriginalFilename string                 `protobuf:"bytes,6,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"` // original filename (e.g. "requests-2.32.3-py3-none-any.whl")
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AIScanRequest) Reset() {
	*x = AIScanRequest{}
	mi := &file_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIScanRequest) ProtoMessage() {}

func (x *AIScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIScanRequest.ProtoReflect.Descriptor instead.
func (*AIScanRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{0}
}

func (x *AIScanRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *AIScanRequest) GetEcosystem() string {
	if x != nil {
		return x.Ecosystem
	}
	return ""
}

func (x *AIScanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AIScanRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AIScanRequest) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *AIScanRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

type AIScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       string                 `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"`                          // "CLEAN" | "SUSPICIOUS" | "MALICIOUS" | "UNKNOWN"
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`                  // 0.0–1.0
	Findings      []string               `protobuf:"bytes,3,rep,name=findings,proto3" json:"findings,omitempty"`                        // e.g. ["base64+exec in .pth", "network call to non-registry host"]
	Explanation   string                 `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`                  // human-readable summary
	ModelUsed     string                 `protobuf:"bytes,6,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`     // e.g. "gpt-5.4-mini"
	TokensUsed    int32                  `protobuf:"varint,7,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"` // for monitoring
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIScanResponse) Reset() {
	*x = AIScanResponse{}
	mi := &file_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIScanResponse) ProtoMessage() {}

func (x *AIScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIScanResponse.ProtoReflect.Descriptor instead.
func (*AIScanResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *AIScanResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *AIScanResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AIScanResponse) GetFindings() []string {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *AIScanResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *AIScanResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *AIScanResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactPath  string                 `protobuf:"bytes,1,opt,name=artifact_path,json=artifactPath,proto3" json:"artifact_path,omitempty"`
	Ecosystem     string                 `protobuf:"bytes,2,opt,name=ecosystem,proto3" json:"ecosystem,omitempty"`
	PackageName   string                 `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_scanner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{2}
}

func (x *ScanRequest) GetArtifactPath() string {
	if x != nil {
		return x.ArtifactPath
	}
	return ""
}

func (x *ScanRequest) GetEcosystem() string {
	if x != nil {
		return x.Ecosystem
	}
	return ""
}

func (x *ScanRequest) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *ScanRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ScanResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Verdict        string                 `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"`
	Confidence     float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Findings       []*Finding             `protobuf:"bytes,3,rep,name=findings,proto3" json:"findings,omitempty"`
	ScannerVersion string                 `protobuf:"bytes,4,opt,name=scanner_version,json=scannerVersion,proto3" json:"scanner_version,omitempty"`
	DurationMs     int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_scanner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{3}
}

func (x *ScanResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *ScanResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ScanResponse) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *ScanResponse) GetScannerVersion() string {
	if x != nil {
		return x.ScannerVersion
	}
	return ""
}

func (x *ScanResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Iocs          []string               `protobuf:"bytes,5,rep,name=iocs,proto3" json:"iocs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_scanner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{4}
}

func (x *Finding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Finding) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Finding) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Finding) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Finding) GetIocs() []string {
	if x != nil {
		return x.Iocs
	}
	return nil
}

type TriageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ecosystem     string                 `protobuf:"bytes,1,opt,name=ecosystem,proto3" json:"ecosystem,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Findings      []*Finding             `protobuf:"bytes,4,rep,name=findings,proto3" json:"findings,omitempty"` // reuse existing Finding message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriageRequest) Reset() {
	*x = TriageRequest{}
	mi := &file_scanner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriageRequest) ProtoMessage() {}

func (x *TriageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriageRequest.ProtoReflect.Descriptor instead.
func (*TriageRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{5}
}

func (x *TriageRequest) GetEcosystem() string {
	if x != nil {
		return x.Ecosystem
	}
	return ""
}

func (x *TriageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TriageRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TriageRequest) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type TriageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      string                 `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"` // "ALLOW" | "QUARANTINE"
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Explanation   string                 `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"` // human-readable reasoning for audit log (max 500 chars)
	ModelUsed     string                 `protobuf:"bytes,4,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,5,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriageResponse) Reset() {
	*x = TriageResponse{}
	mi := &file_scanner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriageResponse) ProtoMessage() {}

func (x *TriageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriageResponse.ProtoReflect.Descriptor instead.
func (*TriageResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{6}
}

func (x *TriageResponse) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *TriageResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TriageResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *TriageResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *TriageResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_scanner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{7}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_scanner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DiffScanRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId         string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Ecosystem          string                 `protobuf:"bytes,2,opt,name=ecosystem,proto3" json:"ecosystem,omitempty"` // pypi, npm, nuget, maven, rubygems, go
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version            string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	PreviousVersion    string                 `protobuf:"bytes,5,opt,name=previous_version,json=previousVersion,proto3" json:"previous_version,omitempty"`
	LocalPath          string                 `protobuf:"bytes,6,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`          // path to NEW artifact on disk (in shared volume)
	PreviousPath       string                 `protobuf:"bytes,7,opt,name=previous_path,json=previousPath,proto3" json:"previous_path,omitempty"` // path to PREVIOUS artifact on disk
	OriginalFilename   string                 `protobuf:"bytes,8,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	LocalPathSha256    string                 `protobuf:"bytes,9,opt,name=local_path_sha256,json=localPathSha256,proto3" json:"local_path_sha256,omitempty"`           // expected hash, bridge re-verifies before extraction (TOCTOU)
	PreviousPathSha256 string                 `protobuf:"bytes,10,opt,name=previous_path_sha256,json=previousPathSha256,proto3" json:"previous_path_sha256,omitempty"` // expected hash, bridge re-verifies before extraction
	PromptVersion      string                 `protobuf:"bytes,11,opt,name=prompt_version,json=promptVersion,proto3" json:"prompt_version,omitempty"`                  // SHA256[:12] of system prompt — bridge attaches to response
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DiffScanRequest) Reset() {
	*x = DiffScanRequest{}
	mi := &file_scanner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffScanRequest) ProtoMessage() {}

func (x *DiffScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffScanRequest.ProtoReflect.Descriptor instead.
func (*DiffScanRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{9}
}

func (x *DiffScanRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *DiffScanRequest) GetEcosystem() string {
	if x != nil {
		return x.Ecosystem
	}
	return ""
}

func (x *DiffScanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiffScanRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DiffScanRequest) GetPreviousVersion() string {
	if x != nil {
		return x.PreviousVersion
	}
	return ""
}

func (x *DiffScanRequest) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *DiffScanRequest) GetPreviousPath() string {
	if x != nil {
		return x.PreviousPath
	}
	return ""
}

func (x *DiffScanRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *DiffScanRequest) GetLocalPathSha256() string {
	if x != nil {
		return x.LocalPathSha256
	}
	return ""
}

func (x *DiffScanRequest) GetPreviousPathSha256() string {
	if x != nil {
		return x.PreviousPathSha256
	}
	return ""
}

func (x *DiffScanRequest) GetPromptVersion() string {
	if x != nil {
		return x.PromptVersion
	}
	return ""
}

type DiffScanResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Verdict        string                 `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"` // CLEAN | SUSPICIOUS | MALICIOUS | UNKNOWN
	Confidence     float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Findings       []string               `protobuf:"bytes,3,rep,name=findings,proto3" json:"findings,omitempty"`
	Explanation    string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	ModelUsed      string                 `protobuf:"bytes,5,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	TokensUsed     int32                  `protobuf:"varint,6,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	FilesAdded     int32                  `protobuf:"varint,7,opt,name=files_added,json=filesAdded,proto3" json:"files_added,omitempty"` // counts so Go can persist without re-parsing payload
	FilesModified  int32                  `protobuf:"varint,8,opt,name=files_modified,json=filesModified,proto3" json:"files_modified,omitempty"`
	FilesRemoved   int32                  `protobuf:"varint,9,opt,name=files_removed,json=filesRemoved,proto3" json:"files_removed,omitempty"`
	PromptVersion  string                 `protobuf:"bytes,10,opt,name=prompt_version,json=promptVersion,proto3" json:"prompt_version,omitempty"`     // SHA256[:12] of system prompt at scan time — Go uses for idempotency cache key (so prompt edits invalidate cache)
	InputTruncated bool                   `protobuf:"varint,11,opt,name=input_truncated,json=inputTruncated,proto3" json:"input_truncated,omitempty"` // bridge sets true when token budget cut content; Go uses for confidence cap defense-in-depth
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DiffScanResponse) Reset() {
	*x = DiffScanResponse{}
	mi := &file_scanner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffScanResponse) ProtoMessage() {}

func (x *DiffScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffScanResponse.ProtoReflect.Descriptor instead.
func (*DiffScanResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{10}
}

func (x *DiffScanResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *DiffScanResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DiffScanResponse) GetFindings() []string {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *DiffScanResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *DiffScanResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *DiffScanResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *DiffScanResponse) GetFilesAdded() int32 {
	if x != nil {
		return x.FilesAdded
	}
	return 0
}

func (x *DiffScanResponse) GetFilesModified() int32 {
	if x != nil {
		return x.FilesModified
	}
	return 0
}

func (x *DiffScanResponse) GetFilesRemoved() int32 {
	if x != nil {
		return x.FilesRemoved
	}
	return 0
}

func (x *DiffScanResponse) GetPromptVersion() string {
	if x != nil {
		return x.PromptVersion
	}
	return ""
}

func (x *DiffScanResponse) GetInputTruncated() bool {
	if x != nil {
		return x.InputTruncated
	}
	return false
}

var File_scanner_proto protoreflect.FileDescriptor

const file_scanner_proto_rawDesc = "" +
	"\n" +
	"\rscanner.proto\x12\ascanner\"\xc8\x01\n" +
	"\rAIScanRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1c\n" +
	"\tecosystem\x18\x02 \x01(\tR\tecosystem\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"local_path\x18\x05 \x01(\tR\tlocalPath\x12+\n" +
	"\x11original_filename\x18\x06 \x01(\tR\x10originalFilename\"\xc8\x01\n" +
	"\x0eAIScanResponse\x12\x18\n" +
	"\averdict\x18\x01 \x01(\tR\averdict\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x1a\n" +
	"\bfindings\x18\x03 \x03(\tR\bfindings\x12 \n" +
	"\vexplanation\x18\x05 \x01(\tR\vexplanation\x12\x1d\n" +
	"\n" +
	"model_used\x18\x06 \x01(\tR\tmodelUsed\x12\x1f\n" +
	"\vtokens_used\x18\a \x01(\x05R\n" +
	"tokensUsed\"\x8d\x01\n" +
	"\vScanRequest\x12#\n" +
	"\rartifact_path\x18\x01 \x01(\tR\fartifactPath\x12\x1c\n" +
	"\tecosystem\x18\x02 \x01(\tR\tecosystem\x12!\n" +
	"\fpackage_name\x18\x03 \x01(\tR\vpackageName\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xc0\x01\n" +
	"\fScanResponse\x12\x18\n" +
	"\averdict\x18\x01 \x01(\tR\averdict\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12,\n" +
	"\bfindings\x18\x03 \x03(\v2\x10.scanner.FindingR\bfindings\x12'\n" +
	"\x0fscanner_version\x18\x04 \x01(\tR\x0escannerVersion\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\"\x93\x01\n" +
	"\aFinding\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x12\n" +
	"\x04iocs\x18\x05 \x03(\tR\x04iocs\"\x89\x01\n" +
	"\rTriageRequest\x12\x1c\n" +
	"\tecosystem\x18\x01 \x01(\tR\tecosystem\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12,\n" +
	"\bfindings\x18\x04 \x03(\v2\x10.scanner.FindingR\bfindings\"\xae\x01\n" +
	"\x0eTriageResponse\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\tR\bdecision\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12 \n" +
	"\vexplanation\x18\x03 \x01(\tR\vexplanation\x12\x1d\n" +
	"\n" +
	"model_used\x18\x04 \x01(\tR\tmodelUsed\x12\x1f\n" +
	"\vtokens_used\x18\x05 \x01(\x05R\n" +
	"tokensUsed\"\x0f\n" +
	"\rHealthRequest\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x9f\x03\n" +
	"\x0fDiffScanRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x1c\n" +
	"\tecosystem\x18\x02 \x01(\tR\tecosystem\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12)\n" +
	"\x10previous_version\x18\x05 \x01(\tR\x0fpreviousVersion\x12\x1d\n" +
	"\n" +
	"local_path\x18\x06 \x01(\tR\tlocalPath\x12#\n" +
	"\rprevious_path\x18\a \x01(\tR\fpreviousPath\x12+\n" +
	"\x11original_filename\x18\b \x01(\tR\x10originalFilename\x12*\n" +
	"\x11local_path_sha256\x18\t \x01(\tR\x0flocalPathSha256\x120\n" +
	"\x14previous_path_sha256\x18\n" +
	" \x01(\tR\x12previousPathSha256\x12%\n" +
	"\x0eprompt_version\x18\v \x01(\tR\rpromptVersion\"\x87\x03\n" +
	"\x10DiffScanResponse\x12\x18\n" +
	"\averdict\x18\x01 \x01(\tR\averdict\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x1a\n" +
	"\bfindings\x18\x03 \x03(\tR\bfindings\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\x12\x1d\n" +
	"\n" +
	"model_used\x18\x05 \x01(\tR\tmodelUsed\x12\x1f\n" +
	"\vtokens_used\x18\x06 \x01(\x05R\n" +
	"tokensUsed\x12\x1f\n" +
	"\vfiles_added\x18\a \x01(\x05R\n" +
	"filesAdded\x12%\n" +
	"\x0efiles_modified\x18\b \x01(\x05R\rfilesModified\x12#\n" +
	"\rfiles_removed\x18\t \x01(\x05R\ffilesRemoved\x12%\n" +
	"\x0eprompt_version\x18\n" +
	" \x01(\tR\rpromptVersion\x12'\n" +
	"\x0finput_truncated\x18\v \x01(\bR\x0einputTruncated2\xdb\x02\n" +
	"\rScannerBridge\x12;\n" +
	"\fScanArtifact\x12\x14.scanner.ScanRequest\x1a\x15.scanner.ScanResponse\x12A\n" +
	"\x0eScanArtifactAI\x12\x16.scanner.AIScanRequest\x1a\x17.scanner.AIScanResponse\x12G\n" +
	"\x10ScanArtifactDiff\x12\x18.scanner.DiffScanRequest\x1a\x19.scanner.DiffScanResponse\x12A\n" +
	"\x0eTriageFindings\x12\x16.scanner.TriageRequest\x1a\x17.scanner.TriageResponse\x12>\n" +
	"\vHealthCheck\x12\x16.scanner.HealthRequest\x1a\x17.scanner.HealthResponseBGZEgithub.com/cloudfieldcz/shieldoo-gate/internal/scanner/guarddog/protob\x06proto3"

var (
	file_scanner_proto_rawDescOnce sync.Once
	file_scanner_proto_rawDescData []byte
)

func file_scanner_proto_rawDescGZIP() []byte {
	file_scanner_proto_rawDescOnce.Do(func() {
		file_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scanner_proto_rawDesc), len(file_scanner_proto_rawDesc)))
	})
	return file_scanner_proto_rawDescData
}

var file_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_scanner_proto_goTypes = []any{
	(*AIScanRequest)(nil),    // 0: scanner.AIScanRequest
	(*AIScanResponse)(nil),   // 1: scanner.AIScanResponse
	(*ScanRequest)(nil),      // 2: scanner.ScanRequest
	(*ScanResponse)(nil),     // 3: scanner.ScanResponse
	(*Finding)(nil),          // 4: scanner.Finding
	(*TriageRequest)(nil),    // 5: scanner.TriageRequest
	(*TriageResponse)(nil),   // 6: scanner.TriageResponse
	(*HealthRequest)(nil),    // 7: scanner.HealthRequest
	(*HealthResponse)(nil),   // 8: scanner.HealthResponse
	(*DiffScanRequest)(nil),  // 9: scanner.DiffScanRequest
	(*DiffScanResponse)(nil), // 10: scanner.DiffScanResponse
}
var file_scanner_proto_depIdxs = []int32{
	4,  // 0: scanner.ScanResponse.findings:type_name -> scanner.Finding
	4,  // 1: scanner.TriageRequest.findings:type_name -> scanner.Finding
	2,  // 2: scanner.ScannerBridge.ScanArtifact:input_type -> scanner.ScanRequest
	0,  // 3: scanner.ScannerBridge.ScanArtifactAI:input_type -> scanner.AIScanRequest
	9,  // 4: scanner.ScannerBridge.ScanArtifactDiff:input_type -> scanner.DiffScanRequest
	5,  // 5: scanner.ScannerBridge.TriageFindings:input_type -> scanner.TriageRequest
	7,  // 6: scanner.ScannerBridge.HealthCheck:input_type -> scanner.HealthRequest
	3,  // 7: scanner.ScannerBridge.ScanArtifact:output_type -> scanner.ScanResponse
	1,  // 8: scanner.ScannerBridge.ScanArtifactAI:output_type -> scanner.AIScanResponse
	10, // 9: scanner.ScannerBridge.ScanArtifactDiff:output_type -> scanner.DiffScanResponse
	6,  // 10: scanner.ScannerBridge.TriageFindings:output_type -> scanner.TriageResponse
	8,  // 11: scanner.ScannerBridge.HealthCheck:output_type -> scanner.HealthResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_scanner_proto_init() }
func file_scanner_proto_init() {
	if File_scanner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scanner_proto_rawDesc), len(file_scanner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scanner_proto_goTypes,
		DependencyIndexes: file_scanner_proto_depIdxs,
		MessageInfos:      file_scanner_proto_msgTypes,
	}.Build()
	File_scanner_proto = out.File
	file_scanner_proto_goTypes = nil
	file_scanner_proto_depIdxs = nil
}
