// scanner-bridge/proto/scanner.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: scanner.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScannerBridge_ScanArtifact_FullMethodName = "/scanner.ScannerBridge/ScanArtifact"
	ScannerBridge_HealthCheck_FullMethodName  = "/scanner.ScannerBridge/HealthCheck"
)

// ScannerBridgeClient is the client API for ScannerBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScannerBridgeClient interface {
	ScanArtifact(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type scannerBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewScannerBridgeClient(cc grpc.ClientConnInterface) ScannerBridgeClient {
	return &scannerBridgeClient{cc}
}

func (c *scannerBridgeClient) ScanArtifact(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, ScannerBridge_ScanArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerBridgeClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ScannerBridge_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScannerBridgeServer is the server API for ScannerBridge service.
// All implementations must embed UnimplementedScannerBridgeServer
// for forward compatibility.
type ScannerBridgeServer interface {
	ScanArtifact(context.Context, *ScanRequest) (*ScanResponse, error)
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedScannerBridgeServer()
}

// UnimplementedScannerBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScannerBridgeServer struct{}

func (UnimplementedScannerBridgeServer) ScanArtifact(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanArtifact not implemented")
}
func (UnimplementedScannerBridgeServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedScannerBridgeServer) mustEmbedUnimplementedScannerBridgeServer() {}
func (UnimplementedScannerBridgeServer) testEmbeddedByValue()                       {}

// UnsafeScannerBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScannerBridgeServer will
// result in compilation errors.
type UnsafeScannerBridgeServer interface {
	mustEmbedUnimplementedScannerBridgeServer()
}

func RegisterScannerBridgeServer(s grpc.ServiceRegistrar, srv ScannerBridgeServer) {
	// If the following call panics, it indicates UnimplementedScannerBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScannerBridge_ServiceDesc, srv)
}

func _ScannerBridge_ScanArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerBridgeServer).ScanArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerBridge_ScanArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerBridgeServer).ScanArtifact(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScannerBridge_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerBridgeServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScannerBridge_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerBridgeServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScannerBridge_ServiceDesc is the grpc.ServiceDesc for ScannerBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScannerBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scanner.ScannerBridge",
	HandlerType: (*ScannerBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScanArtifact",
			Handler:    _ScannerBridge_ScanArtifact_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ScannerBridge_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scanner.proto",
}
