package builtin

import "github.com/cloudfieldcz/shieldoo-gate/internal/scanner"

// popularPackageSeed contains the top popular packages per ecosystem.
// Used to seed the popular_packages DB table on first run, and to additively
// extend it (ON CONFLICT DO NOTHING) on every subsequent startup so that new
// entries propagate to existing DBs without manual intervention.
//
// Sources: PyPI download stats, npm download counts, RubyGems stats, Maven Central
// downloads, Go pkg.go.dev, Docker Hub pulls (2026-Q1).
//
// Adding a name here causes Strategy 1 (exact-match) to short-circuit for it,
// preventing false-positive edit-distance hits against another popular package
// (e.g., "vitest" vs "vite", "nest" vs "next").
var popularPackageSeed = map[scanner.Ecosystem][]string{
	scanner.EcosystemPyPI: {
		"requests", "boto3", "urllib3", "setuptools", "typing-extensions",
		"botocore", "certifi", "idna", "charset-normalizer", "python-dateutil",
		"packaging", "s3transfer", "pyyaml", "numpy", "pip",
		"six", "jmespath", "cryptography", "cffi", "wheel",
		"pycparser", "attrs", "platformdirs", "pyasn1", "colorama",
		"filelock", "tomli", "importlib-metadata", "zipp", "jinja2",
		"markupsafe", "click", "pytz", "pygments", "pydantic",
		"fsspec", "pydantic-core", "decorator", "wrapt", "jsonschema",
		"more-itertools", "pluggy", "aiohttp", "protobuf", "grpcio",
		"pandas", "scipy", "pillow", "matplotlib", "tqdm",
		"flask", "django", "sqlalchemy", "celery", "redis",
		"psycopg2", "gunicorn", "httpx", "fastapi", "uvicorn",
		"pyjwt", "paramiko", "docker", "pytest", "coverage",
		"black", "mypy", "ruff", "isort", "flake8",
		"beautifulsoup4", "lxml", "scrapy", "selenium", "playwright",
		"networkx", "scikit-learn", "tensorflow", "torch", "transformers",
		"openai", "anthropic", "langchain", "boto3-stubs", "aws-cdk-lib",
		"azure-core", "azure-storage-blob", "google-cloud-storage", "google-auth",
		"rich", "typer", "httptools", "uvloop", "orjson",
		"pynacl", "bcrypt", "passlib", "itsdangerous", "werkzeug",
		"alembic", "mako", "greenlet", "gevent", "eventlet",
		// 2026-Q1 expansion — frequent transitive deps and ML/data ecosystem leaders.
		"python-dotenv", "huggingface-hub", "tokenizers", "safetensors", "datasets",
		"accelerate", "xgboost", "lightgbm", "scikit-image", "ipython",
		"jupyter", "ipykernel", "notebook", "nbformat", "nbconvert",
		"pyarrow", "polars", "websockets", "pyzmq", "tornado",
		"pre-commit", "tox", "pip-tools", "pytest-asyncio", "pytest-mock",
		"pytest-cov", "pytest-django", "responses", "freezegun", "factory-boy",
		"djangorestframework", "django-cors-headers", "flask-sqlalchemy", "flask-login", "flask-cors",
		"python-multipart", "email-validator", "authlib", "python-jose", "azure-identity",
		"opencv-python", "kombu", "amqp", "billiard", "vine",
		"frozenlist", "multidict", "yarl", "aiosignal", "anyio",
		"sniffio", "h11", "httpcore", "starlette", "asgiref",
	},
	scanner.EcosystemNPM: {
		"lodash", "chalk", "react", "express", "commander",
		"axios", "debug", "moment", "request", "async",
		"tslib", "fs-extra", "glob", "uuid", "semver",
		"minimist", "yargs", "inquirer", "rxjs", "bluebird",
		"underscore", "jquery", "typescript", "webpack", "eslint",
		"prettier", "babel-core", "next", "vue", "angular",
		"mocha", "jest", "chai", "sinon", "supertest",
		"dotenv", "cors", "body-parser", "cookie-parser", "helmet",
		"mongoose", "sequelize", "prisma", "knex", "pg",
		"redis", "ioredis", "socket.io", "ws", "node-fetch",
		"rimraf", "mkdirp", "cross-env", "concurrently", "nodemon",
		"pm2", "winston", "pino", "morgan", "bunyan",
		"jsonwebtoken", "passport", "bcryptjs", "crypto-js", "jose",
		"zod", "joi", "yup", "ajv", "class-validator",
		"tailwindcss", "postcss", "autoprefixer", "sass", "less",
		"d3", "three", "chart.js", "recharts", "highcharts",
		"puppeteer", "playwright", "cheerio", "jsdom", "happy-dom",
		"aws-sdk", "@aws-sdk/client-s3", "@azure/storage-blob", "@google-cloud/storage",
		"graphql", "apollo-server", "type-graphql", "nexus", "pothos",
		"esbuild", "vite", "rollup", "parcel", "turbopack",
		// 2026-Q1 expansion — addresses vitest/vite false positive and other near-collisions.
		"vitest", "@types/node", "@types/react", "@types/express", "@types/jest",
		"@nestjs/core", "@nestjs/common", "@nestjs/platform-express", "typeorm", "nest",
		"nuxt", "gatsby", "astro", "svelte", "@sveltejs/kit",
		"solid-js", "remix", "@remix-run/react", "tsx", "ts-node",
		"tsup", "@swc/core", "swc-loader", "nanoid", "lru-cache",
		"date-fns", "dayjs", "luxon", "validator", "bcrypt",
		"nodemailer", "multer", "compression", "csurf", "express-rate-limit",
		"express-validator", "passport-local", "passport-jwt", "kafkajs", "amqplib",
		"bull", "bullmq", "agenda", "node-cron", "node-cache",
		"firebase", "firebase-admin", "stripe", "twilio", "@sendgrid/mail",
		"kleur", "picocolors", "prompts", "ora", "boxen",
		"meow", "cac", "arg", "loglevel", "pino-pretty",
		"react-dom", "react-router", "react-router-dom", "redux", "@reduxjs/toolkit",
		"react-redux", "zustand", "jotai", "@tanstack/react-query", "@tanstack/query-core",
		"framer-motion", "styled-components", "@emotion/react", "@emotion/styled", "clsx",
		"classnames", "immer", "@mui/material", "@mui/icons-material", "@chakra-ui/react",
		"antd", "tslint", "babel-loader", "ts-loader",
		"husky", "lint-staged", "vitepress", "docusaurus", "@docusaurus/core",
	},
	scanner.EcosystemRubyGems: {
		"rails", "rake", "bundler", "rspec", "nokogiri",
		"rack", "activesupport", "actionpack", "activerecord", "actionview",
		"puma", "sidekiq", "devise", "pg", "redis",
		"minitest", "capybara", "selenium-webdriver", "webdrivers", "faker",
		"rubocop", "simplecov", "aws-sdk", "json", "rest-client",
		"faraday", "httparty", "sinatra", "thin", "unicorn",
		// 2026-Q1 expansion.
		"bcrypt", "i18n", "tzinfo", "concurrent-ruby", "loofah",
		"mail", "mime-types", "globalid", "marcel", "rails-dom-testing",
		"rails-html-sanitizer", "actionmailer", "actionmailbox", "actiontext", "activejob",
		"activemodel", "activestorage", "actioncable", "railties", "pry",
		"pry-byebug", "pry-rails", "byebug", "factory_bot", "factory_bot_rails",
		"database_cleaner", "webmock", "vcr", "shoulda-matchers", "oj",
		"multi_json", "connection_pool", "kaminari", "will_paginate", "paper_trail",
		"pundit", "cancancan", "delayed_job", "resque", "omniauth",
		"omniauth-oauth2", "dotenv-rails", "bootsnap", "listen", "spring",
		"rspec-rails", "rspec-core", "rspec-mocks", "rspec-expectations",
		"rubocop-rails", "rubocop-rspec", "rubocop-performance",
		"sprockets-rails", "turbo-rails", "stimulus-rails", "importmap-rails",
		"propshaft", "view_component", "solid_queue", "solid_cache",
	},
	scanner.EcosystemNuGet: {
		"Newtonsoft.Json", "System.Text.Json", "Serilog", "AutoMapper",
		"MediatR", "FluentValidation", "Dapper", "EntityFramework",
		"xunit", "NUnit", "Moq", "Polly", "Swashbuckle",
		"Microsoft.Extensions.DependencyInjection", "Microsoft.AspNetCore.Mvc",
		// 2026-Q1 expansion — fills out the .NET ecosystem coverage.
		"Microsoft.EntityFrameworkCore", "Microsoft.EntityFrameworkCore.SqlServer",
		"Microsoft.EntityFrameworkCore.Design", "Microsoft.EntityFrameworkCore.Tools",
		"Microsoft.EntityFrameworkCore.InMemory", "Microsoft.EntityFrameworkCore.Relational",
		"Microsoft.Extensions.Logging", "Microsoft.Extensions.Logging.Abstractions",
		"Microsoft.Extensions.Configuration", "Microsoft.Extensions.Configuration.Json",
		"Microsoft.Extensions.Configuration.Binder", "Microsoft.Extensions.Hosting",
		"Microsoft.Extensions.Http", "Microsoft.Extensions.Caching.Memory",
		"Microsoft.Extensions.Caching.Abstractions", "Microsoft.Extensions.Options",
		"Microsoft.Extensions.Primitives", "Microsoft.AspNetCore.Authentication.JwtBearer",
		"Microsoft.AspNetCore.OpenApi", "Microsoft.NET.Test.Sdk",
		"Microsoft.IdentityModel.Tokens", "Microsoft.IdentityModel.JsonWebTokens",
		"System.IdentityModel.Tokens.Jwt", "Microsoft.Data.SqlClient",
		"Microsoft.Net.Http.Headers", "coverlet.collector", "coverlet.msbuild",
		"FluentAssertions", "Bogus", "RestSharp",
		"NLog", "NLog.Web.AspNetCore", "log4net",
		"Quartz", "Hangfire", "Hangfire.AspNetCore", "Hangfire.SqlServer",
		"IdentityServer4", "Castle.Core",
		"StackExchange.Redis", "MongoDB.Driver", "MongoDB.Bson",
		"Npgsql", "Npgsql.EntityFrameworkCore.PostgreSQL",
		"Pomelo.EntityFrameworkCore.MySql",
		"Azure.Identity", "Azure.Storage.Blobs", "Azure.Storage.Queues",
		"Azure.Messaging.ServiceBus", "AWSSDK.Core", "AWSSDK.S3",
		"MailKit", "MimeKit", "Stripe.net", "Twilio",
		"RabbitMQ.Client", "MassTransit", "Confluent.Kafka",
		"OpenTelemetry", "OpenTelemetry.Extensions.Hosting", "prometheus-net",
		"Refit", "Mapster",
	},
	scanner.EcosystemDocker: {
		"nginx", "alpine", "ubuntu", "node", "python",
		"postgres", "redis", "mysql", "mongo", "golang",
		"openjdk", "httpd", "traefik", "consul", "vault",
		// 2026-Q1 expansion.
		"debian", "busybox", "fedora", "rockylinux", "almalinux",
		"mariadb", "memcached", "rabbitmq", "elasticsearch", "kibana",
		"logstash", "prometheus", "grafana", "caddy", "php",
		"ruby", "rust", "wordpress", "nextcloud", "drupal",
		"jenkins", "minio", "sonarqube", "keycloak", "gitlab",
	},
	scanner.EcosystemMaven: {
		// Top Maven Central artifacts in groupId:artifactId form. Format must match
		// what the Maven adapter passes to the scanner (see internal/adapter/maven/maven.go).
		"com.fasterxml.jackson.core:jackson-databind",
		"com.fasterxml.jackson.core:jackson-core",
		"com.fasterxml.jackson.core:jackson-annotations",
		"com.google.guava:guava",
		"org.apache.commons:commons-lang3",
		"commons-io:commons-io",
		"org.apache.commons:commons-collections4",
		"org.springframework:spring-core",
		"org.springframework:spring-context",
		"org.springframework:spring-web",
		"org.springframework:spring-webmvc",
		"org.springframework:spring-tx",
		"org.springframework:spring-jdbc",
		"org.springframework.boot:spring-boot",
		"org.springframework.boot:spring-boot-starter",
		"org.springframework.boot:spring-boot-starter-web",
		"org.springframework.boot:spring-boot-starter-data-jpa",
		"org.springframework.boot:spring-boot-starter-test",
		"org.springframework.security:spring-security-core",
		"junit:junit",
		"org.junit.jupiter:junit-jupiter",
		"org.junit.jupiter:junit-jupiter-api",
		"org.junit.jupiter:junit-jupiter-engine",
		"org.mockito:mockito-core",
		"org.mockito:mockito-junit-jupiter",
		"org.assertj:assertj-core",
		"org.hamcrest:hamcrest",
		"org.slf4j:slf4j-api",
		"ch.qos.logback:logback-classic",
		"ch.qos.logback:logback-core",
		"org.apache.logging.log4j:log4j-core",
		"org.apache.logging.log4j:log4j-api",
		"org.apache.logging.log4j:log4j-slf4j2-impl",
		"org.hibernate:hibernate-core",
		"org.hibernate.orm:hibernate-core",
		"mysql:mysql-connector-java",
		"com.mysql:mysql-connector-j",
		"org.postgresql:postgresql",
		"com.h2database:h2",
		"org.apache.httpcomponents:httpclient",
		"org.apache.httpcomponents.client5:httpclient5",
		"com.squareup.okhttp3:okhttp",
		"com.squareup.retrofit2:retrofit",
		"com.google.code.gson:gson",
		"com.google.protobuf:protobuf-java",
		"io.grpc:grpc-core",
		"io.grpc:grpc-stub",
		"io.grpc:grpc-protobuf",
		"io.netty:netty-all",
		"io.netty:netty-handler",
		"org.json:json",
		"javax.servlet:javax.servlet-api",
		"jakarta.servlet:jakarta.servlet-api",
		"javax.persistence:javax.persistence-api",
		"jakarta.persistence:jakarta.persistence-api",
		"org.projectlombok:lombok",
		"io.jsonwebtoken:jjwt-api",
		"io.jsonwebtoken:jjwt-impl",
		"io.jsonwebtoken:jjwt-jackson",
		"org.testcontainers:testcontainers",
		"org.testcontainers:junit-jupiter",
		"org.testcontainers:postgresql",
		"io.reactivex.rxjava3:rxjava",
		"io.projectreactor:reactor-core",
		"com.zaxxer:HikariCP",
		"org.flywaydb:flyway-core",
		"org.liquibase:liquibase-core",
		"io.micrometer:micrometer-core",
		"io.micrometer:micrometer-registry-prometheus",
		"io.opentelemetry:opentelemetry-api",
		"io.opentelemetry:opentelemetry-sdk",
		"redis.clients:jedis",
		"org.apache.kafka:kafka-clients",
		"co.elastic.clients:elasticsearch-java",
		"software.amazon.awssdk:s3",
		"software.amazon.awssdk:dynamodb",
	},
	scanner.EcosystemGo: {
		// Top Go modules by import count. Format must match what the Go adapter
		// passes to the scanner — full module path including host.
		"github.com/gin-gonic/gin",
		"github.com/gorilla/mux",
		"github.com/labstack/echo/v4",
		"github.com/go-chi/chi/v5",
		"github.com/gofiber/fiber/v2",
		"github.com/spf13/cobra",
		"github.com/spf13/viper",
		"github.com/spf13/pflag",
		"github.com/sirupsen/logrus",
		"github.com/rs/zerolog",
		"go.uber.org/zap",
		"github.com/google/uuid",
		"github.com/golang-jwt/jwt/v5",
		"github.com/golang-jwt/jwt/v4",
		"github.com/jmoiron/sqlx",
		"github.com/mattn/go-sqlite3",
		"github.com/lib/pq",
		"github.com/jackc/pgx/v5",
		"github.com/jackc/pgx/v4",
		"github.com/go-sql-driver/mysql",
		"github.com/redis/go-redis/v9",
		"github.com/go-redis/redis/v8",
		"go.mongodb.org/mongo-driver",
		"github.com/stretchr/testify",
		"github.com/golang/mock",
		"go.uber.org/mock",
		"github.com/google/go-cmp",
		"github.com/onsi/ginkgo/v2",
		"github.com/onsi/gomega",
		"google.golang.org/grpc",
		"google.golang.org/protobuf",
		"github.com/golang/protobuf",
		"github.com/prometheus/client_golang",
		"github.com/prometheus/common",
		"github.com/aws/aws-sdk-go",
		"github.com/aws/aws-sdk-go-v2",
		"github.com/Azure/azure-sdk-for-go",
		"cloud.google.com/go",
		"cloud.google.com/go/storage",
		"github.com/google/go-containerregistry",
		"github.com/coreos/go-oidc/v3",
		"golang.org/x/oauth2",
		"golang.org/x/sync",
		"golang.org/x/crypto",
		"golang.org/x/net",
		"golang.org/x/text",
		"golang.org/x/time",
		"golang.org/x/exp",
		"golang.org/x/tools",
		"gopkg.in/yaml.v3",
		"gopkg.in/yaml.v2",
		"github.com/pkg/errors",
		"github.com/json-iterator/go",
		"github.com/spf13/afero",
		"github.com/fatih/color",
		"github.com/mattn/go-isatty",
		"github.com/hashicorp/go-multierror",
		"github.com/hashicorp/go-hclog",
		"github.com/hashicorp/go-version",
		"github.com/hashicorp/consul/api",
		"github.com/hashicorp/vault/api",
		"github.com/dgraph-io/ristretto",
		"github.com/patrickmn/go-cache",
		"github.com/robfig/cron/v3",
		"github.com/google/wire",
		"go.opentelemetry.io/otel",
		"go.opentelemetry.io/otel/sdk",
		"go.opentelemetry.io/otel/trace",
		"go.opentelemetry.io/otel/metric",
		"github.com/cenkalti/backoff/v4",
		"github.com/avast/retry-go",
		"github.com/swaggo/swag",
		"github.com/swaggo/gin-swagger",
		"entgo.io/ent",
		"gorm.io/gorm",
		"gorm.io/driver/postgres",
		"gorm.io/driver/mysql",
		"github.com/uptrace/bun",
		"github.com/IBM/sarama",
		"github.com/segmentio/kafka-go",
		"github.com/elastic/go-elasticsearch/v8",
		"github.com/olivere/elastic/v7",
	},
}
